### ISSUE TITLE
Missing files for running the demo (Refinement/demo.py)

### ISSUE THREAD

**Issue by thkptl** [uniBruce/Mead#1]
Hello,

Thank you for sharing your work. I tried to run the demo (Refinement/demo.py), but found that some files are missing, especially "./lists/pca.pickle". I think I understand what it means, but there is no code to show how to compute it from the training data, and could you please share the pickle file if possible? 

Also when I tried to run Refinement/demo.py, there seems no page2em() in Refinement/utils_parallel.py and can I use page2emo() in Refinement/trainer_demo.py instead? 

Thank you!

**Comment by uniBruce** [comment]
Hi, I have uploaded the pca.pickle, and processing file for pca (i.e., preprocess_ldmk.py) as well. 

The page2em function in Refinement/utils_parallel.py is a mistake, sorry about that. In terms of the page2emo function in Refinement/trainer_demo.py, actually it was designed for the data folders at the early stage, maybe not very useful for the data you can access from Google drive. You can easily set up both emotion and intensity as a 11-dimension one-hot vector as described in the Readme, which I strongly recommend.

**Comment by uniBruce** [comment]
> Hello,
> 
> Thank you for sharing your work. I tried to run the demo (Refinement/demo.py), but found that some files are missing, especially "./lists/pca.pickle". I think I understand what it means, but there is no code to show how to compute it from the training data, and could you please share the pickle file if possible?
> 
> Also when I tried to run Refinement/demo.py, there seems no page2em() in Refinement/utils_parallel.py and can I use page2emo() in Refinement/trainer_demo.py instead?
> 
> Thank you!

Hi, I have uploaded the pca.pickle, and processing file for pca (i.e., preprocess_ldmk.py) as well.

The page2em function in Refinement/utils_parallel.py is a mistake, sorry about that. In terms of the page2emo function in Refinement/trainer_demo.py, actually it was designed for the data folders at the early stage, maybe not very useful for the data you can access from Google drive. You can easily set up both emotion and intensity as a 11-dimension one-hot vector as described in the Readme, which I strongly recommend.

**Comment by ssinha89** [comment]
Hi, When I try to run demo.py under Refinement module after modifying the paths to the model files and list files appropriately, files audio_test_all.txt and video_list_test.txt (specified in config_demo.yml) appear to be missing. Also what should be the variable gan_path in config_demo.yml  be set to ?
