### ISSUE TITLE
How to inference on my own reference image?

### ISSUE THREAD

**Issue by angus0119** [uniBruce/Mead#10]
Thank you for great work! But I have an issue with getting results.

When I run test.py with my own image, I get a poor result like below.
![gen_459](https://user-images.githubusercontent.com/84361124/120917428-3f34bd80-c6ea-11eb-947b-80cba5742867.jpg)
What should i do to get the better result?

**Comment by uniBruce** [comment]
This work is right now based on single-person generation. Btw, the released model is based on the actor M003. We are still working on the cross-person version.
