### ISSUE TITLE
Audio pickle donot match image from video

### ISSUE THREAD

**Issue by Neroaway** [uniBruce/Mead#13]
Hi, when I use the preprocess_mfcc.py to create audio.pickle, I fine the number of  pickle donot match the number of image from video. ie . `angry/level_1/001.m4a`  create  97 pickle, but `video/front/angry/level_1/001.mp4` create 98 images. 
Have you encountered this problem and how to solve it？
Thank you!

**Comment by yChenN1** [comment]
I met the same problem as you. For . angry/level_1/001.m4a create 97 pickle, but for video/front/angry/level_1/001.mp4 create 98 images. Have you solved this problem?  Thks!

**Comment by 2351548518** [comment]
我也遇到了这个问题，我发现数据中的音频比视频短一点。你是怎么解决这个问题的呢？谢谢

I'm also having this issue and I'm finding that the audio in the data is a bit shorter than the video. How did you solve this problem? Thank you
