### ISSUE TITLE
Audio clips with duration >7 seconds

### ISSUE THREAD

**Issue by mjschlauch** [uniBruce/Mead#14]
Thanks for your efforts in producing the MEAD dataset. We are looking forward to working with it.

It seems to me that some audio clips are longer than the maximum duration suggested in the paper. The supplementary material Fig 1 plots as well as the text on the first page suggests that the maximum "sentence duration" is 7 seconds. 
https://wywu.github.io/projects/MEAD/support/MEAD-supp.pdf

From my example below I believe you should be able to replicate a case where the duration is 17 seconds. To replicate, you could try downloading the audio.tar file for M034 from Google Drive, extracting and then running the following python code:
```
>>> import librosa
>>> sentence_path = './fear/level_3/028.m4a'
>>> y, sr = librosa.load(sentence_path, sr=None)
>>> librosa.get_duration(y=y, sr=sr)
17.237333333333332
>>> sr
48000
>>> librosa.__version__
'0.8.1'
```

**Comment by uniBruce** [comment]
> Thanks for your efforts in producing the MEAD dataset. We are looking forward to working with it.
> 
> It seems to me that some audio clips are longer than the maximum duration suggested in the paper. The supplementary material Fig 1 plots as well as the text on the first page suggests that the maximum "sentence duration" is 7 seconds. https://wywu.github.io/projects/MEAD/support/MEAD-supp.pdf
> 
> From my example below I believe you should be able to replicate a case where the duration is 17 seconds. To replicate, you could try downloading the audio.tar file for M034 from Google Drive, extracting and then running the following python code:
> 
> ```
> >>> import librosa
> >>> sentence_path = './fear/level_3/028.m4a'
> >>> y, sr = librosa.load(sentence_path, sr=None)
> >>> librosa.get_duration(y=y, sr=sr)
> 17.237333333333332
> >>> sr
> 48000
> >>> librosa.__version__
> '0.8.1'
> ```

Sorry for the inconvenience, does the corresponding video has the same problem? Maybe the 17-second-audio is a combination of 4 audio clips. I will contact the data group to check it.
