### ISSUE TITLE
How to generate image(384x384) from video?

### ISSUE THREAD

**Issue by Neroaway** [uniBruce/Mead#15]
Hi,Thanks for your works!However, you code donot include the code(generate image from video).I think this very code is important for this work. Could you release the code?Thank you very much!

**Comment by uniBruce** [comment]
> Hi,Thanks for your works!However, you code donot include the code(generate image from video).I think this very code is important for this work. Could you release the code?Thank you very much!

The easiest way is to use FFMPEG, with the command "ffmpeg -r 30 -f image2 -i gen_%04d.jpg <img_path>  -vcodec libx264  test.mp4"
