### ISSUE TITLE
Why is 403 displayed at the end of downloading video data？

### ISSUE THREAD

**Issue by Baenny** [uniBruce/Mead#16]
Hi, thanks for your project.
Now I have a problem that there is 403 error displayed in the end of downloading video data, but it's ok when downloading audio data. Can u give some solutions?
![image](https://user-images.githubusercontent.com/38773999/128009963-eda275d2-5888-449d-843b-5d031c311c6e.png)

**Comment by uniBruce** [comment]
We met some issues when using Google drive, so please use Baidu drive if possible.

link: https://pan.baidu.com/s/1zYKz19kmQH6vnO2nogPk4Q
code: th8e
@cocoaw
