### ISSUE TITLE
The demo.py file does not work well, how to set the para of 'gan_path'?'

### ISSUE THREAD

**Issue by QUTGXX** [uniBruce/Mead#17]
> Hi, I am unable to run the demo code to generate the facial images. When I try to run demo.py under Refinement module after modifying the paths to the model files and list files appropriately, files audio_test_all.txt and video_list_test.txt (specified in config_demo.yml) appear to be missing. Also what should be the variable gan_path in config_demo.yml be set to ?

Actually, when running demo.py, you just need a single file. I have uploaded it, namely audio_demo.txt, and also the reference image. By the way, please feel free to download the testing audio data, which is provided on google drive.

_Originally posted by @uniBruce in https://github.com/uniBruce/Mead/issues/3#issuecomment-821160951_

**Comment by QUTGXX** [comment]
![image](https://user-images.githubusercontent.com/36947214/130543663-d72e4b4d-a350-4a6c-824b-e2ed92dcb7a7.png)
It still raise the error.

**Comment by uniBruce** [comment]
> ![image](https://user-images.githubusercontent.com/36947214/130543663-d72e4b4d-a350-4a6c-824b-e2ed92dcb7a7.png) It still raise the error.

It seems the bug exists in the loading process. Make sure you loaded the right checkpoint file first.
