### ISSUE TITLE
Speech Corpus Text Files

### ISSUE THREAD

**Issue by filby89** [uniBruce/Mead#18]
Thank you for making your dataset and method available. I would like to ask if the text of the corpus in txt (or other form) is available somewhere, or do we need to take it from the supplementary material of the pdf?

**Comment by uniBruce** [comment]
> Thank you for making your dataset and method available. I would like to ask if the text of the corpus in txt (or other form) is available somewhere, or do we need to take it from the supplementary material of the pdf?

Oh, the texts are included in the supplementary file, please fell free to use it.
