### ISSUE TITLE
Link to Pretrained models

### ISSUE THREAD

**Issue by ssinha89** [uniBruce/Mead#2]
Hi,
Thanks for releasing the dataset and the code. The link for the pretrained models needed for running the test code is currently not working, could you kindly update the repository with the correct hyperlink?

**Comment by uniBruce** [comment]
> Hi,
> Thanks for releasing the dataset and the code. The link for the pretrained models needed for running the test code is currently not working, could you kindly update the repository with the correct hyperlink?

Hi, sorry for the broken hyperlink. I have already updated the link.

**Comment by ssinha89** [comment]
Thanks :) I have been able to download from the link.
