### ISSUE TITLE
Demo code error

### ISSUE THREAD

**Issue by ssinha89** [uniBruce/Mead#3]
Hi, I am unable to run the demo code to generate the facial images. When I try to run demo.py under Refinement module after modifying the paths to the model files and list files appropriately, files audio_test_all.txt and video_list_test.txt (specified in config_demo.yml) appear to be missing. Also what should be the variable gan_path in config_demo.yml be set to ?

**Comment by PerfectBlueFeynman** [comment]
Thank you for this brilliant dataset. I want to go through the code step by step, but the same problems came as missing those list.txt files. Could you upload or at least put something about how to generate those files?

**Comment by ssinha89** [comment]
Can you please share a working demo code for the image generation ?

**Comment by sbsws88** [comment]
@uniBruce Hi is there any update on these files audio_test_all.txt and video_list_test.txt? I am unable to run the demo code.

**Comment by uniBruce** [comment]
> Hi, I am unable to run the demo code to generate the facial images. When I try to run demo.py under Refinement module after modifying the paths to the model files and list files appropriately, files audio_test_all.txt and video_list_test.txt (specified in config_demo.yml) appear to be missing. Also what should be the variable gan_path in config_demo.yml be set to ?

Actually, when running demo.py, you just need a single file. I have uploaded it, namely audio_demo.txt, and also the reference image. By the way, please feel free to download the testing audio data, which is provided on google drive.
