### ISSUE TITLE
Few issues when running demo

### ISSUE THREAD

**Issue by Yusics** [uniBruce/Mead#5]
Hi:

I really appreciated you guys released the source code. But would you mind to test the demo.py by yourselves? There are several issues when running demo.py

(1) When cd Refinement as suggested, there are several paths are wrong.
(2) The audio dim (the size of phoneme) is 28 instead 97 in your config_demo.yaml. 
(3) Line 290 in data.py should be './MFCC_test' instead of '/MFCC_test' in your code
(4) Line 308 in data.py, sample is a string looks like 'M003_73_1_output_03/054.pickle reference.jpg'. I don't think sample[0] in the following lines are referring to the character M. Currently I split the sample (which is a string) by space
(5) Line 60 in traner_demo.py, heatmap = self.transform(draw_heatmap_from_78_landmark(fake_ldmk, 384, 384)). You forgot the batchsize argument (the 1st argument of the draw_heatmap_from_78_landmark function). I supposed the batchsize=1 during the demo.
(6) Following (5), the fake_ldmk should resize to 2-D numpy array which is (1, 78).
(7) Following (6), the type of the returned draw_heatmap_from_78_landmark should be np array PIL image format but the current function returned tensor
(8) Line 66 in demo.py, trainer.page2emo instead of trainer.page2em
(9) In demo.py, image_dir = os.path.join(image_directory, str(em_fc)) instead of image_dir = os.path.join(image_directory, em_fc)

Really appreciate your great work but will definitely be more grateful if you could test the demo program first. Thanks!

**Comment by uniBruce** [comment]
Thanks for the advice, and I have tried to correct these mistakes.
