### ISSUE TITLE
Some question about Refinement network

### ISSUE THREAD

**Issue by JoeFang123** [uniBruce/Mead#6]
I found there are some bugs in the demo.py. For example, the parameters in function _draw_heatmap_from_78_landMark_ is lack when the function is called, then the parameters _w_ and _h_ is inverted. 

When I tried to fix these bugs, the following outputs appears:
N2E result: 
![N2E](https://user-images.githubusercontent.com/33960231/115486187-bae8c100-a288-11eb-90d5-a95425ecd587.png)

Audio2Landmark result:
![HeatMap](https://user-images.githubusercontent.com/33960231/115486203-c340fc00-a288-11eb-92d0-5d63bb0cffa1.png)

Refinement result:
![RefineImage](https://user-images.githubusercontent.com/33960231/115486230-cdfb9100-a288-11eb-985c-95d418938854.png)

It is obvious that the final result, which is Refinement result, has too much noise. I wonder whether the N2E and Audio2Landmark network is normal, and how to get an accurate output of Refinement network.

**Comment by Janie1996** [comment]
N2E result

**Comment by Janie1996** [comment]
N2E result

**Comment by Janie1996** [comment]
hi, these are my results 
N2E Result:
![gen_001](https://user-images.githubusercontent.com/9865151/115748141-7cf2b680-a3c8-11eb-9b2e-e32281e1f041.jpg)
Refinement result:
![gen_001](https://user-images.githubusercontent.com/9865151/115748216-8b40d280-a3c8-11eb-93be-7587afa2fa8e.jpg)

why these  different with yours?

**Comment by uniBruce** [comment]
> I found there are some bugs in the demo.py. For example, the parameters in function _draw_heatmap_from_78_landMark_ is lack when the function is called, then the parameters _w_ and _h_ is inverted.
> 
> When I tried to fix these bugs, the following outputs appears:
> N2E result:
> ![N2E](https://user-images.githubusercontent.com/33960231/115486187-bae8c100-a288-11eb-90d5-a95425ecd587.png)
> 
> Audio2Landmark result:
> ![HeatMap](https://user-images.githubusercontent.com/33960231/115486203-c340fc00-a288-11eb-92d0-5d63bb0cffa1.png)
> 
> Refinement result:
> ![RefineImage](https://user-images.githubusercontent.com/33960231/115486230-cdfb9100-a288-11eb-985c-95d418938854.png)
> 
> It is obvious that the final result, which is Refinement result, has too much noise. I wonder whether the N2E and Audio2Landmark network is normal, and how to get an accurate output of Refinement network.

Sorry for the mistake. I have updated the draw_heatmap_from_78_landMark function in Refinement/utils_parallel.py. You can try first to check if the results are normal.
