### ISSUE TITLE
Baidu Drive download link expired 

### ISSUE THREAD

**Issue by julianyulu** [uniBruce/Mead#7]
Hi, 

Thanks for sharing, but it seem that the MEAD download link from Baidu Drive is invalid now. Would you please provide a new one ? 

Thanks, 
Julian

**Comment by uniBruce** [comment]
> Hi,
> 
> Thanks for sharing, but it seem that the MEAD download link from Baidu Drive is invalid now. Would you please provide a new one ?
> 
> Thanks,
> Julian

Hi, Julian. As the dataset belongs to Sensetime Research, we can only provide the data by using Google drive. Our colleagues are still working on the storage issues of Google drive.
