### ISSUE TITLE
the dataset of Baidu Drive has been out of date

### ISSUE THREAD

**Issue by jlygit** [uniBruce/Mead#8]
hello,
https://wywu.github.io/projects/MEAD/MEAD.html
the dataset of [Download-Part0 (Baidu Drive)] has been out of date. can you share again？

**Comment by iGuaZi** [comment]
![image](https://user-images.githubusercontent.com/17562965/127611400-9aa2b86a-f28a-4721-b649-24d4b365db19.png)
google drive 也下载不了哦

**Comment by wywu** [comment]
link: https://pan.baidu.com/s/1zYKz19kmQH6vnO2nogPk4Q
code: th8e
@jlygit @iGuaZi

**Comment by BaMarcy** [comment]
Hi! is it possible to register to Baidu from EU?

**Comment by flckv** [comment]
I am not able to access the webpage: 
![image](https://github.com/uniBruce/Mead/assets/103381497/ae2979ed-b900-4b64-aac0-1e896f48765c)

Can you provide an alternative way of accessing (google drive / huggingface / ?), please?

**Comment by flckv** [comment]
I am not sure what to do with the Netdisk client?
This file also wants to be downloaded: BaiduNetdisk_mac_4.26.0_x64.dmg 

I get messages: 

安装完成后，重启浏览器即可高速下载


你下载的内容包含文件夹，请使用百度网盘客户端下载。
安装最新版网盘客户端

**Comment by NaMoCv** [comment]
> link: https://pan.baidu.com/s/1zYKz19kmQH6vnO2nogPk4Q code: th8e 代码：th8e @jlygit @iGuaZi

439G？给给发一个只有Neutral类的吗？🙏

**Comment by wzx7084** [comment]
请问下载文件后，发现小于18G的视频都是损坏的，能否发一下未损坏的数据集 @wywu

**Comment by wzx7084** [comment]
> > link: https://pan.baidu.com/s/1zYKz19kmQH6vnO2nogPk4Q code: th8e 代码：th8e @jlygit @iGuaZi
> 
> 439G？给给发一个只有Neutral类的吗？🙏

请问您找到只有neytral的数据了吗？

**Comment by wzx7084** [comment]
> > link: https://pan.baidu.com/s/1zYKz19kmQH6vnO2nogPk4Q code: th8e 代码：th8e @jlygit @iGuaZi
> 
> 439G？给给发一个只有Neutral类的吗？🙏

请问您找到neutral的数据了吗？ @NaMoCv
