### ISSUE TITLE
MEAD - Missing views for speaker W017

### ISSUE THREAD

**Issue by miraodasilva** [uniBruce/Mead#9]
I downloaded the full Part 0 from Google Drive, and am planning to use this dataset for my research. However, while preprocessing it I noticed that many views are missing from speaker W017 (it looks like the only view that exists is "down"). Is this intended? Do you plan on releasing these extra views in the future? Thanks.

**Comment by uniBruce** [comment]
Sorry for the mistake. I will contact the related staff to check these problems.

**Comment by miraodasilva** [comment]
Thanks! Furthermore, it appears M019 and M011 are also missing some emotions and views, I can send you a full list of missing folders.

**Comment by uniBruce** [comment]
> Thanks! Furthermore, it appears M019 and M011 are also missing some emotions and views, I can send you a full list of missing folders.

Could you please send the list to my email? Thanks for reminding me. I should notice the related staff for further work.

**Comment by miraodasilva** [comment]
Sure, can you let me know your email please? I could not find it anywhere.

**Comment by uniBruce** [comment]
> Sure, can you let me know your email please? I could not find it anywhere.

bruce_gluttony@outlook.com. Thanks for that.
